### ISSUE TITLE
Stack traces are broken

### ISSUE THREAD

**Issue by dcastro** [myfreeweb/hspec-expectations-pretty-diff#3]
Using stackage lts-13.7, when `shouldBe` fails, the call stack seems to always be:

```
src/Test/Hspec/Expectations/Pretty.hs:86:22:
```

I did some digging around it seems like `shouldBe` asks GHC for an implicit `?loc :: CallStack`.
Under the hood, `shouldBe` calls `Test.HUnit.assertFailure` which, up until version 1.3.1.2, also expected an implicit `?loc` and everything woked fine.
See: https://hackage.haskell.org/package/HUnit-1.3.1.2/docs/Test-HUnit-Base.html#v:assertFailure

Starting at HUnit 1.4.0.0 though, `assertFailure` now expects the "standardized" `?callStack :: CallStack`, and because the implicit param names no longer match up, the call stack gets lost when `assertFailure` is called.
See: https://hackage.haskell.org/package/HUnit-1.4.0.0/docs/Test-HUnit-Base.html#v:assertFailure

I had a go at submitting a PR to fix this, and it seems there's two ways of doing this:

1. Putting a lower bound on the HUnit dependency of `>= 1.4.0.0`, and changing `shouldBe`  and friends to request a `?callStack` instead of a `?loc`
2. or continue supporting all versions of HUnit, but use an `#if` directive to choose which implicit param to use. I.e.:
```haskell
#if defined(HAS_SOURCE_LOCATIONS) && MIN_VERSION_hunit(1,4,0,0)

import           GHC.Stack

#define with_loc(NAME, TYPE) NAME :: (?callStack :: CallStack) => TYPE

#elif defined(HAS_SOURCE_LOCATIONS)

import           GHC.Stack

#define with_loc(NAME, TYPE) NAME :: (?loc :: CallStack) => TYPE

#else

#define with_loc(NAME, TYPE) NAME :: TYPE

#endif
```

Since the `MIN_VERSION_pkgname(x,y,z)` macro is only [available in GHC 8.0+](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/phases.html#standard-cpp-macros), this means that going with option 2 requires bumping this package's stackage snapshot from lts-5.9 to at least lts-7.24.

What are your thoughts on this?

**Comment by valpackett** [comment]
oh, the stackage snapshot should be bumped to the **latest** lts. The preprocessor stuff in this case is very simple and you already wrote it, so let's go with that :)
