### ISSUE TITLE
Can you make a release?

### ISSUE THREAD

**Issue by ncaq** [myfreeweb/hspec-expectations-pretty-diff#9]
I write [added: unicode-show by ncaq · Pull Request #8 · unrelentingtech/hspec-expectations-pretty-diff](https://github.com/unrelentingtech/hspec-expectations-pretty-diff/pull/8).

I want release this verson.
The reason is that I don't have to write a lot of stuff in stack.yaml to specify repositories, etc. if you do the release.
I'm sure your great package will get more use.

**Comment by valpackett** [comment]
Released 0.7.2.6
